/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.playit;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author User
 */
public class NewJFrameDisplaySong extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameDisplaySong
     */
    long total_length;
    long pouse;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    
    File myfile = null;
    
    
    
    
    public NewJFrameDisplaySong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_play = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_pause = new javax.swing.JButton();
        btn_resume = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/playit/play.jpg"))); // NOI18N
        btn_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_playMouseReleased(evt);
            }
        });
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        btn_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/playit/stop.jpg"))); // NOI18N
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_stopMouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/playit/headset.jpg"))); // NOI18N

        lbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 0, 102));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        btn_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/playit/pause.jpg"))); // NOI18N
        btn_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pauseMouseReleased(evt);
            }
        });

        btn_resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/playit/resume.jpg"))); // NOI18N
        btn_resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_resumeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playMouseReleased
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        
        int val = chooser.showOpenDialog(null);
        
        if(val==JFileChooser.APPROVE_OPTION)
        {
            myfile = chooser.getSelectedFile();
            String song = myfile+"";
            
            String name = chooser.getSelectedFile().getName();
            lbl.setText(name);
        }
        
        try{
            FIS = new FileInputStream(myfile);
            BIS = new BufferedInputStream(FIS);
            player = new Player(BIS);
            total_length = FIS.available();
            
            new Thread()
            {
                public void run()
                {
                    try
                    {
                        player.play();
                    }
                    
                    catch(JavaLayerException ex)
                    {
                        Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE, null,ex);
                    }
                }
            }.start();
        }
        
        catch(JavaLayerException ex)
        {
            Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE, null,ex);
        }
        
        catch(IOException ex)
        {
            Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE, null,ex);
        } 
    }//GEN-LAST:event_btn_playMouseReleased

    private void btn_pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pauseMouseReleased
        // TODO add your handling code here:
        if (player!=null)
        {
            try{
                pouse = FIS.available();
                player.close();
            }
            
            catch(IOException ex)
            {
              Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_btn_pauseMouseReleased

    private void btn_resumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resumeMouseReleased
        // TODO add your handling code here:
        try{
            FIS = new FileInputStream(myfile);
            BIS = new BufferedInputStream(FIS);
            player = new Player(BIS);
            
            FIS.skip(total_length-pouse);
            
            new Thread()
            {
                public void run()
                {
                    try{
                        player.play();
                    }
                    
                    catch(JavaLayerException ex)
                    {
                        Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
            }.start();                   
        }
        
        catch(IOException ex)
        {
            Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        catch(JavaLayerException ex)
        {
            Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_resumeMouseReleased

    private void btn_stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stopMouseReleased
        // TODO add your handling code here:
        if(player!=null)
        {
            player.close();
            lbl.setText(null);
        }
    }//GEN-LAST:event_btn_stopMouseReleased

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDisplaySong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameDisplaySong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pause;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_resume;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
